# Generated by Django 6.0.3 on 2026-03-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='annulee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campagne',
            name='capacite_par_creneau',
            field=models.PositiveIntegerField(default=10, help_text='Nombre max de donneurs par créneau horaire'),
        ),
    ]
